OS := $(shell uname)
SHELL := /bin/bash
INPATH := /
PATH := $(SHELL)

run-app:
	@echo '==================== $(PATH)$(INPATH) ==================='
	npm install
	npm run build
	npm start

what:
	@echo '==================== $(PATH)$(INPATH) ==================='
