OS := $(shell uname)
SHELL := /bin/bash

run-app:
	@echo '==================== $(PATH)$(INPATH) ==================='
	npm install
	npm run build
	npm start

what:
	@echo '==================== $(PATH)$(INPATH) ==================='
